### ISSUE TITLE
Result or Validator in the Appliction layer?

### ISSUE THREAD

**Issue by hhko** [dr-marek-jaskula/DomainDrivenDesignUniversity#161]
In the application layer, a mixture of _validator and Result is being used to handle failure.

- Result.Failure
  - Output Validation: https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Application/Features/Users/Queries/GetUserByUsername/GetUserByUsernameQueryHandler.cs#L23-L26
- _validator.Failure
  - Input Validation: https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Application/Features/Users/Queries/GetRolePermissions/GetRolePermissionsQueryHandler.cs#L21-L27
  - Output Validation: https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Application/Features/Users/Queries/GetRolePermissions/GetRolePermissionsQueryHandler.cs#L32-L38

Wouldn't it be better to unify it by using _validator?

**Comment by dr-marek-jaskula** [comment]
Indeed, I will change it in upcoming pr, where I will add Login using Google feature. Thanks for finding it, lastly I have less time to work on this project (therefore I am coding a bit too fast), but hopefully I will find some. Google login should be done soon (1-2 days). Kubernetes still in progress.
