### ISSUE TITLE
Question:  What is the scope of input validation?

### ISSUE THREAD

**Issue by hhko** [dr-marek-jaskula/DomainDrivenDesignUniversity#168]
I think [this code should be handled by input validation](https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Application/Features/Users/Commands/DeletePermission/DeletePermissionCommandHandler.cs#L18-L26).

If it move to input validation(Ex. `... Validator.Fluent.cs`), the Handler code will be simpler as shown below.

```cs
// Before
var parsePermissionNameResult = Enum.TryParse<PermissionName>(command.PermissionName, out var permissionName);
_validator.If(
   parsePermissionNameResult is false, 
   Error.InvalidArgument($"{command.PermissionName} is not a valid PermissionName"));

if (_validator.IsInvalid)
{
    return _validator.Failure();
}

// After
var permissionName = Enum.Parse<PermissionName>(command.PermissionName);
```

**Comment by dr-marek-jaskula** [comment]
Hey,

pull request #169 was added to move this validation to fluent validation (with additional extension metod for enums).

In this pr there a change for performance - next memory cache was introduced (for caching ValidationResultCache) so that in FluentValidationPipeline we dont need to call CreateValidationResult that used reflection and casting to object. Nevertheless, it comes with complexity (in cache initialization). So if for someone complecity is too big, he can use CreateValidationResult in old way.

Additionally, there were so minor fix.

**Comment by dr-marek-jaskula** [comment]
If there are no more questions about this topic I close this issue.

**Comment by hhko** [comment]
@dr-marek-jaskula 

If method `"public static TResult CreateValidationResult<TResult>(this ICollection<Error> errors)"` is used, [an exception occurs](https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Domain/Common/Errors/ErrorUtilities.cs#L24).
```cs
.MakeGenericType(typeof(TResult).GenericTypeArguments[0])
```

This is because method ["MustBeAnEnum"](https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Application/Utilities/FluentValidationUtilities.cs#L169) does not use `IList<Error>`.
I think method ["CreateValidationResult"](https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Domain/Common/Errors/ErrorUtilities.cs#L14) needs improvement.

**Comment by dr-marek-jaskula** [comment]
@hhko

Recently I added additional check

```csharp
        if (typeof(TResult) == typeof(Result) || typeof(TResult) == typeof(IResult))
        {
            return (ValidationResult.WithErrors(errors) as TResult)!;
        }
```

this part `typeof(TResult) == typeof(IResult)` should fix the problem.

Additionally, I extended MustBeAnEnum method also by additional check

```csharp
            if (int.TryParse(value, out var _) || Enum.TryParse<TEnum>(value, out var _) is false)
            {
                context.AddFailure(Error.InvalidArgument($"'{value}' is not a valid {typeof(TEnum).Name}").Serialize());
            }
```

This part 
`int.TryParse(value, out var _)`
Will secure the user input like '4'.

Use the latest version to check it
