### ISSUE TITLE
How do you plan to manage the dependencies of domain classes in the future?

### ISSUE THREAD

**Issue by hhko** [dr-marek-jaskula/DomainDrivenDesignUniversity#4]
- **Congratulations! first release.**
- A domain has no dependencies.  
  However, the domain is being accessed from an area other than the domain core, such as Persistence.
- I wonder if there are plans to develop in the future to prevent domain access from an area other than the domain core, such as Persistence.
- ex. Customer is domain. https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Persistence/Configurations/CustomerConfiguration.cs#L20

**Comment by dr-marek-jaskula** [comment]
Thank You for your support and this issue ;)

I did not have any plans for preventing the access to the domain from such layers as Persistance. Could You descripe or give an example of the behavior when the Domain Core is only presented outside. How, for instance, the Customer configuration would be able to only refer the Domain Core? I am not familiar with this architecutre approach, so I would be grateful if You share Your thoughts or provide some external materiasl so I can learn a bit about this.

I really appreciate your contribution. Feel free to give some ideas or create pull requests to upgrade this repository. Then, more people would benefit form better code ;)

**Comment by hhko** [comment]
Hi. Sorry for the very late feedback.
I can learn a lot from this repository code, thank you very much.

I recently read "[Get Your Hands Dirty on Clean Architecture: A hands-on guide to creating clean web applications with code examples in Java 1st Edition](https://www.amazon.com/Hands-Dirty-Clean-Architecture-hands/dp/1839211962)" book.
 - Youtube: https://www.youtube.com/watch?v=cPH5AiqLQTo
 - ppt: https://speakerdeck.com/thombergs/o-2019?slide=40
   - Mapping strategies
     - Two Way Mapping
     - No Mapping
     - Full Mapping(Command Pattern per Use Case)
     - Mix & Match

In my opinion, a mapping strategy is very important to secure domains for maintenance.
I’d love to hear your thoughts the mapping strategy for evolving this repository.

**Comment by hhko** [comment]
I completely agree with you. 
I would like to actively participate in your opinions.
