### ISSUE TITLE
AggregateRoot and Entity where (generic type constraint) are different. Is this right?

### ISSUE THREAD

**Issue by hhko** [dr-marek-jaskula/DomainDrivenDesignUniversity#6]
AggregateRoot and Entity where (generic type constraint) are different. Is this right?
| class | where |
| --- | --- |
| AggregateRoot | where TEntityId : struct, `IEntityId<TEntityId>` |
| Entity | where TEntityId : struct, `IEntityId` |

<br/>

### AggregateRoot
https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/76b968948c7c5ce5590f944bc8ba470dc5fa7bad/src/Shopway.Domain/BaseTypes/AggregateRoot.cs#L11

### Entity
https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/76b968948c7c5ce5590f944bc8ba470dc5fa7bad/src/Shopway.Domain/BaseTypes/Entity.cs#L6

**Comment by dr-marek-jaskula** [comment]
This is a proper notice ;) thanks for spotting this issue. I am still looking for ways to improve this repository, however I recently I have less time to work on it. Therefore, thanks again;)
